### ISSUE TITLE
[question] is there a example for TVG-RADIO?

### ISSUE THREAD

**Issue by www2000** [HamzaBhf00/m3u-tags-iptv#2]
I wand to know is there any example for TVG-RADIO the only mention that i can find is you article in this repo.

**Comment by HamzaBhf00** [comment]
This example demonstrates how the "TVG-Radio" tag is used alongside other metadata tags within a playlist to differentiate between radio and TV channels:
#EXTM3U
#EXTINF:-1 tvg-id="radio1" tvg-name="Radio Station 1" tvg-radio="true",Radio Station 1
http://radio1stream.com/stream

#EXTINF:-1 tvg-id="tv1" tvg-name="TV Channel 1" tvg-radio="false",TV Channel 1
http://tvchannel1stream.com/stream
--------------
NOTE: 
tvg-radio="true" or tvg-radio="false" is the "TVG-Radio" tag indicating whether the channel is a radio channel (true) or a TV channel (false).

**Comment by www2000** [comment]
Thanks can you add the value type for the TVG tags as bool (true/false), string, int, float, url, etc?
